In [2]:
import numpy as np
import keras
from keras.preprocessing import image
import os

Using TensorFlow backend.


In [3]:
CAT_PATH = "../Hackdata/cataugmentation/"
DOG_PATH = "../Hackdata/dog/"
PIG_PATH = "../Hackdata/piga/"
COW_PATH = "../Hackdata/CowAugmentation/"
MONKEY_PATH = "../Hackdata/monkeyAugmentation/"
STRAY_PATH = "../Hackdata/StrayDog/"

In [4]:
def load_image(path):
    #img = image.load_img(path, target_size=(224,224,3))
    img = cv2.imread(path,1)
    img = cv2.resize(img, (224, 224))
    img = img / 255.0
    img = image.img_to_array(img)
    return img

In [5]:
import cv2

In [6]:
cat_images=[]

cat_list = os.listdir(CAT_PATH)

for ix in range(len(cat_list)/2):
    cat_images.append(load_image(CAT_PATH + str(cat_list[ix])))

cat_images = np.asarray(cat_images)

In [7]:
print cat_images.shape

np.save("../Hackdata/cat_images.npy", cat_images[:800])

(915, 224, 224, 3)


In [8]:
dog_images=[]

dog_list = os.listdir(DOG_PATH)

for ix in range(len(dog_list)/2):
    dog_images.append(load_image(DOG_PATH + str(dog_list[ix])))
    
dog_images = np.asarray(dog_images)

In [9]:
print dog_images.shape

np.save("../Hackdata/dog_images.npy", dog_images[:2000])

(5749, 224, 224, 3)


In [10]:
pig_images=[]

pig_list = os.listdir(PIG_PATH)

for ix in range(len(pig_list)/2):
    pig_images.append(load_image(PIG_PATH + str(pig_list[ix])))
    
pig_images = np.asarray(pig_images)

In [11]:
print pig_images.shape

np.save("../Hackdata/pig_images.npy", pig_images[:800])

(945, 224, 224, 3)


In [12]:
cow_images=[]

cow_list = os.listdir(COW_PATH)

for ix in range(len(cow_list)/2):
    cow_images.append(load_image(COW_PATH + str(cow_list[ix])))
    
cow_images = np.asarray(cow_images)

In [13]:
print cow_images.shape

np.save("../Hackdata/cow_images.npy", cow_images[:800])

(895, 224, 224, 3)


In [14]:
stray_images=[]

stray_list = os.listdir(STRAY_PATH)

for ix in range(len(stray_list)/2):
    stray_images.append(load_image(STRAY_PATH + str(stray_list[ix])))
    
stray_images = np.asarray(stray_images)

In [15]:
print stray_images.shape

np.save("../Hackdata/stray_images.npy", stray_images[:1200])

(1610, 224, 224, 3)


In [16]:
monkey_images=[]

monkey_list = os.listdir(MONKEY_PATH)

for ix in range(len(monkey_list)/2):
    monkey_images.append(load_image(MONKEY_PATH + str(monkey_list[ix])))
    
monkey_images = np.asarray(monkey_images)

In [17]:
print monkey_images.shape

np.save("../Hackdata/monkey_images.npy", monkey_images[:800])

(925, 224, 224, 3)


In [18]:
cat_images = np.load("../Hackdata/cat_images.npy")
dog_images = np.load("../Hackdata/dog_images.npy")
pig_images = np.load("../Hackdata/pig_images.npy")
cow_images = np.load("../Hackdata/cow_images.npy")
monkey_images = np.load("../Hackdata/monkey_images.npy")
stray_images = np.load("../Hackdata/stray_images.npy")

print cat_images.shape
print dog_images.shape
print pig_images.shape
print cow_images.shape
print monkey_images.shape
print stray_images.shape

data = np.concatenate((cat_images, dog_images, pig_images, cow_images, monkey_images, stray_images), axis=0)
print data.shape
np.save("./data.npy", data)

(800, 224, 224, 3)
(2000, 224, 224, 3)
(800, 224, 224, 3)
(800, 224, 224, 3)
(800, 224, 224, 3)
(1200, 224, 224, 3)
(6400, 224, 224, 3)


In [19]:
print monkey_images[0]

[[[ 0.14901961  0.43137255  0.35294119]
  [ 0.14901961  0.43137255  0.35294119]
  [ 0.1254902   0.40392157  0.32549021]
  ..., 
  [ 0.41960785  0.68627453  0.65882355]
  [ 0.41568628  0.68235296  0.65490198]
  [ 0.41568628  0.68235296  0.65490198]]

 [[ 0.14901961  0.43137255  0.35294119]
  [ 0.14901961  0.43137255  0.35294119]
  [ 0.12941177  0.40392157  0.32549021]
  ..., 
  [ 0.41960785  0.68627453  0.65882355]
  [ 0.41568628  0.68235296  0.65490198]
  [ 0.41568628  0.68235296  0.65490198]]

 [[ 0.13333334  0.41176471  0.33333334]
  [ 0.13333334  0.41176471  0.33333334]
  [ 0.12156863  0.39215687  0.31764707]
  ..., 
  [ 0.43137255  0.69411767  0.66666669]
  [ 0.42352942  0.68627453  0.65882355]
  [ 0.42352942  0.68627453  0.65882355]]

 ..., 
 [[ 0.23529412  0.32156864  0.39215687]
  [ 0.23529412  0.32156864  0.39215687]
  [ 0.23921569  0.32549021  0.39607844]
  ..., 
  [ 0.09019608  0.14509805  0.23529412]
  [ 0.09019608  0.14509805  0.23529412]
  [ 0.09019608  0.14509805  0.23529